### ISSUE TITLE
Test 22D - Unable to view list of direct download URLs

### ISSUE THREAD

**Issue by millercathy** [modc08/modc08#81] opened 2015-05-15 06:22 UTC
Testing in IE9
Viewing Dataset - select files - Click Show Download URLs button - Download URLs popup does not display.
Checked pop-up blocker - turned pop-up blocker off. Retested. Download URLs do not display.
@shundezhang Can you please see if you can replicate in IE?

**Comment by millercathy** [comment] 2015-05-19 00:10
I'll test this again....

**Comment by shundezhang** [comment] 2015-05-19 00:12
@millercathy Sorry we had some network and nectar issue in the last few days and I haven't been able to test this. I'll do it today.

**Comment by millercathy** [comment] 2015-05-19 00:20
No worries @shundezhang I will test again also in IE11
This is fairly low priority; #74 and #73 are more important

**Comment by shundezhang** [comment] 2015-05-19 02:26
I did some tests and only IE 9 works. Any version earlier than that is incompatible with Javascripts used in Mytardis. IE 10 and 11 should work in theory. Maybe we should tell the users to use IE 9 or newer versions.

**Comment by shundezhang** [comment] 2015-05-19 05:27
This is caused by class 'fade'. Here is the issue: https://github.com/twbs/bootstrap/issues/3672

Obviously it has been fixed in the newer version of bootstrap. The modal dialog example in bootstrap official website works well. The latest version of bootstrap is 3.3.4 but the version is mytardis is 2.0.4 which is really old. It is a lot of work to migrate from 2.x to 3.0 since bootstrap 3.0 is NOT backwards compatible with 2.x: http://getbootstrap.com/migration/. Also mytardis uses a bunch of other javascript libraries that may (or may not) depend on bootstrap.

Therefore a 'quick' fix is applied.

**Comment by millercathy** [comment] 2015-05-19 06:19
Thanks @shundezhang 
Over to @franksc for closing

**Comment by franksc** [comment] 2015-05-19 07:06
Workaround seems reasonable.

Friends Don't Let Friends Use Internet Explorer

**Closed as completed by franksc** 2015-05-19 07:06 UTC
Labels: bug
